name 'maestrodev-maestro'
version '2.0.7'

author 'maestrodev'
license 'Apache License, Version 2.0'
project_page 'http://github.com/maestrodev/puppet-maestro'
source 'http://github.com/maestrodev/puppet-maestro'
summary 'MaestroDev Maestro'
description 'Install and configure Maestro from MaestroDev'

dependency 'maestrodev/wget',       '>=1.3.0'
dependency 'maestrodev/maven',      '>=1.0.0'
dependency 'puppetlabs/stdlib',     '>=3.2.0'
dependency 'puppetlabs/postgresql', '>=3.0.0'
dependency 'joshcooper/powershell', '>=0.0.6'
