name 'maestrodev-maestro_nodes'
version '1.7.0'

author 'maestrodev'
license 'Apache License, Version 2.0'
project_page 'http://github.com/maestrodev/puppet-maestro_nodes'
source 'http://github.com/maestrodev/puppet-maestro_nodes'
summary 'Maestro related services'
description 'Maestro related services installation and configuration: jenkins, sonar, archiva,...'

dependency 'puppetlabs/stdlib', '>=3.2.0'
dependency 'maestrodev/ant', '>=1.0.5'
dependency 'maestrodev/archiva', '>=1.0.0'
dependency 'maestrodev/git', '>=1.0.0'
dependency 'maestrodev/svn', '>=1.0.0'
dependency 'rtyler/jenkins', '>=1.1.0'
dependency 'maestrodev/maestro', '>=2.0.0'
dependency 'maestrodev/maven', '>=0.0.2'
dependency 'maestrodev/sonar', '>=1.0.0'
dependency 'maestrodev/rvm', '>=1.4.0'
dependency 'maestrodev/ssh_keygen', '>=1.0.0'
dependency 'puppetlabs/mongodb', '0.3.0'
dependency 'maestrodev/activemq', '>=2.0.0'
dependency 'puppetlabs/java', '>=0.3.0'
dependency 'puppetlabs/ntp', '>=3.0.0'
dependency 'stahnma/epel', '>=0.0.6'
dependency 'maestrodev/statsd', '>=1.0.0'
dependency 'puppetlabs/nodejs', '>=0.3.0'
dependency 'jfryman/nginx', '>= 0.0.7'
dependency 'saz/ssh', '>=1.2.0'
