#! /bin/sh
### BEGIN INIT INFO
# Provides:          statsd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: statsd
# Description:       Runs statsd
#
### END INIT INFO

# Author: Ben Hughes <ben@puppetlabs.com>
#

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="statsd"
NAME="statsd"
DAEMON="/usr/local/sbin/statsd"
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

. /lib/init/vars.sh

. /lib/lsb/init-functions

# Exit if the package is not installed
if ! [ -x "$DAEMON" ]; then
  echo "'${DAEMON}' does not exist or is not executable" >&2
  exit 5
fi


start() {
  log_daemon_msg "Starting $DESC" "$NAME"

  # Return
  #   0 if daemon has been started
  #   1 if daemon was already running
  #   2 if daemon could not be started
  start-stop-daemon --start --quiet --pidfile $PIDFILE --background \
                    --make-pidfile --chuid nobody --exec $DAEMON -- $DAEMON_ARGS
  RETVAL=$?
  log_end_msg $RETVAL
  return $RETVAL
}

stop() {
  log_daemon_msg "Stopping $DESC" "$NAME"
  # Return
  #   0 if daemon has been stopped
  #   1 if daemon was already stopped
  #   2 if daemon could not be stopped
  #   other if a failure occurred
  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name node
  RETVAL=$?
  # Many daemons don't delete their pidfiles when they exit.
  log_end_msg $RETVAL
  return $RETVAL
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status_of_proc "$DAEMON" "$NAME"
    exit $?
    ;;
  restart|force-reload)
    stop
    start
    ;;
  *)
  echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
  exit 3
  ;;
esac
