name    'maestrodev-activemq'
version '2.0.0'
source 'http://github.com/maestrodev/puppet-activemq.git'
author 'maestrodev'
license 'Apache License, Version 2.0'
summary 'Install and manage Apache ActiveMQ'
description 'Install Apache ActiveMQ and manage the service'
project_page 'http://github.com/maestrodev/puppet-activemq'

dependency 'maestrodev/wget', '>=1.0.0'
dependency 'puppetlabs/stdlib'
